cron: "@every 1h"
filename-prefix: "consul-snapshot-"
file-extension: ".snap"

consul:
    url: http://127.0.0.1:8500
    token: ""
    lock-key: "consul-snapshot/.lock"
    lock-timeout: "10m"
    
local:
    destination-path: "/tmp/snapshots"

azure-blob:
    container-name: "container_name"
    container-path: "consul/snapshots"
    storage-account: "azure_account"
    # storage-access-key: ""

outputs:
    - "local"
    - "azure_blob"
